image: node-image

matrix:
  - env: c=1

install:
  -  apt-get install python3-venv
  -  python3 -m venv venv
  -  . venv/bin/activate
  -  pip install -r requirements.txt

script:
  - . venv/bin/activate
  -  pytest

cache:
  - python_model