image: python3.6

matrix:
  - env: c=1

install:
  -  python3 -m venv venv
  -  . venv/bin/activate
  -  pip3 install -r requirements.txt

script:
  -  . venv/bin/activate
  -  pytest

cache:
  - ./venv