image: node-image

matrix:
  - env: c=1

install:
  -  sudo apt-get install python3-venv -y
  -  sudo apt install python3-pip -y
  -  python3 -m venv venv
  -  . venv/bin/activate
  -  pip3 install -r requirements.txt

script:
  -  . venv/bin/activate
  -  python3 -m pytest

cache:
  - ./venv